"""Reproducible static site generator. Only public customer-profile content is imported."""
from pathlib import Path
import ast, html, json, re
from PIL import Image

ROOT = Path(__file__).parent
OUT = ROOT / 'dist'
SOURCE = Path(r'C:\Users\alpha\OneDrive\Desktop\AlphaIT Engineering')
PROFILE = SOURCE / '00_COMMERCIAL_COMMAND/05_COMMERCIAL_DOCUMENTS/01_ALPHAIT/_build_company_profile_and_proposal_20260911.py'
if PROFILE.exists():
 tree = ast.parse(PROFILE.read_text(encoding='utf-8-sig'))
 expr = next(n.value for n in tree.body if isinstance(n, ast.Assign) and any(isinstance(t, ast.Name) and t.id == 'PRODUCTS' for t in n.targets))
 products = eval(compile(ast.Expression(expr), '<profile data>', 'eval'), {'__builtins__': {}}, {'FLOW_ORANGE':'F67411','COBALT':'2F5BFF'})
else:
 products = json.loads((ROOT/'products.json').read_text(encoding='utf-8'))
products.sort(key=lambda p: 0 if p['name']=='Verdika' else 1)
SLUGS = {'Verdika':'verdika','Varren':'varren','Varren Aegis':'varren-aegis','Varren Herald':'varren-herald','LisBon Signal Infrastructure (LSI)':'lisbon-signal','LisBon Trust Infrastructure (LTI)':'lisbon-trust','LisCredit Marketplace':'liscredit','Trust App':'trust-app','LisBon Flow Infrastructure (LFI)':'lisbon-flow','Flow App':'flow-app','Pollenair':'pollenair','Focused AlphaIT Build':'business-systems-engineering'}
ICONS = {'verdika':'verdika-mark','varren':'varren-mark','aegis':'varren-aegis-mark','herald':'varren-herald-mark','lsi':'lsi-mark','lisbon':'lisbon-icon','liscredit':'liscredit-mark','lfi':'lfi-mark','flow':'flow-mark','pollenair':'pollenair-mark','alphait':'alphait-mark'}
BUYERS = {
 'Verdika':'Businesses, institutions and public bodies that need to understand customer, employee or public experience.',
 'Varren':'Organisations that need research, plans, content, approvals and authorised commercial action to work together.',
 'Varren Aegis':'Teams responsible for live websites, platforms and digital services.',
 'Varren Herald':'Service businesses and platform teams that want to bring customers back for a useful, timely reason.',
 'LisBon Signal Infrastructure (LSI)':'Banks, lenders, fintechs and teams that need reliable signals from financial records.',
 'LisBon Trust Infrastructure (LTI)':'Banks, lenders, fintechs and capital providers assessing individuals, businesses or institutions.',
 'LisCredit Marketplace':'Banks, fintechs and funds looking for relevant, evidence-backed credit applications.',
 'Trust App':'Lenders and institutions that need a clear financial-profile and credit-application journey for customers.',
 'LisBon Flow Infrastructure (LFI)':'Transport, logistics and delivery businesses that want connected operations under their own brand.',
 'Flow App':'Transport and logistics businesses that need a connected booking and service experience for customers and drivers.',
 'Pollenair':'Institutions, employers and sponsors running practical skills programmes.',
 'Focused AlphaIT Build':'Organisations whose service, process or new offering cannot be served fully by an existing system.'}
MEASURES = ['Feedback reaching the right stakeholder; time to respond; recurring issues.','Time from brief to approval; completed actions; verified delivery records.','Time to detect issues; time to resolve them; successful repeat checks.','Recovered customer journeys; contact quality; response and opt-out rates.','Review time; records requiring investigation; completeness of decision evidence.','Decision turnaround; policy consistency; affordability and exposure records.','Relevant applications; time to review; progress through provider decisions.','Profile completion; application completion; customer support requests.','Booking completion; delivery time; dispatch effort; settlement exceptions.','Booking completion; status enquiries; completed journeys.','Participation; progress; completion; learners needing support.','The agreed change in cost, time, service quality, visibility or revenue opportunity.']
for p,m in zip(products,MEASURES):
 p['slug']=SLUGS[p['name']]; p['icon']=ICONS[p['icon_key']]+'.png'; p['buyer']=BUYERS[p['name']];p['measure']=m

e = html.escape
arrow = '<span aria-hidden="true">↗</span>'
def action(label, href, style='primary'):
 return f'<a class="button {style}" href="{e(href)}">{label}{arrow}</a>'
def header(current=''):
 def link(name, href): return f'<a href="{href}"'+(' aria-current="page"' if current==name else '')+f'>{name}</a>'
 return '<a class="skip" href="#main">Skip to content</a><header class="header" data-header><a class="identity" href="index.html" aria-label="AlphaIT Engineering home"><img src="assets/brand/AlphaIT_Alpha_Aperture_Mono_Carbon.svg" alt="" width="30" height="30"><span>AlphaIT <small>Engineering</small></span></a><button class="menu-toggle" aria-label="Open navigation" aria-expanded="false" aria-controls="main-nav">Menu <span aria-hidden="true">＋</span></button><nav id="main-nav" aria-label="Main navigation">'+link('Our systems','platforms.html')+link('How we work','engagements.html')+link('Company','company.html')+'<a class="nav-contact" href="contact.html">Let’s talk '+arrow+'</a></nav></header>'

def close(title='What could work better?', text='Show us the operation, missed opportunity or new service you have in mind. We will help you find the right starting point.'):
 return f'<section class="closing"><div class="closing-kicker"><img src="assets/brand/AlphaIT_Alpha_Aperture_Reverse_Pearl.svg" width="38" height="38" alt=""><p class="eyebrow">Your next step</p></div><h2>{title}</h2><p>{text}</p><div class="actions">{action("Show us the work","contact.html","light")}<a class="text-link" href="AlphaIT-Company-and-Product-Profile.pdf" target="_blank" rel="noopener">Read our company profile <span aria-hidden="true">↗</span></a></div><div class="closing-rule"></div><a class="closing-email" href="mailto:projects@alphaitengineering.com">projects@alphaitengineering.com {arrow}</a></section>'
def footer():
 return '<footer><div class="footer-top"><a class="footer-brand" href="index.html">AlphaIT Engineering</a><p>Product Engineering.<br>Without Limits.</p><div><a href="AlphaIT-Company-and-Product-Profile.pdf" target="_blank" rel="noopener">Company &amp; product profile ↗</a><a href="https://wa.me/254792989676" target="_blank" rel="noopener">WhatsApp ↗</a><a href="contact.html">Start a conversation ↗</a></div></div><div class="addresses"><div><h3>United Arab Emirates</h3><p>Alpha Innovation Technologies - F.Z.C<br>B.C. 1301279, Ajman Free Zone C1 Building<br>Ajman Free Zone, Ajman<br>United Arab Emirates</p></div><div><h3>Kenya</h3><p>Neptune, Mararo Road<br>Lavington, Nairobi<br>Kenya</p></div><div><h3>Nigeria</h3><p>Polaris Bank Building<br>30 Marina Street, CMS Bus Stop<br>Lagos Island, Nigeria</p></div></div><div class="footer-bottom"><span>© 2026 AlphaIT Engineering</span><a href="mailto:projects@alphaitengineering.com">projects@alphaitengineering.com</a><a href="https://alphaitengineering.com">alphaitengineering.com ↗</a></div></footer>'

def page(file,title,description,body,current=''):
 text=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)} | AlphaIT Engineering</title><meta name="description" content="{e(description)}"><meta name="theme-color" content="#f7f3ec"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(description)}"><meta property="og:image" content="https://alphaitengineering.com/assets/brand/AlphaIT_Aether_Mineral_OpenGraph.png"><meta name="robots" content="noindex,nofollow"><link rel="icon" href="assets/brand/AlphaIT_Favicon.svg"><link rel="preload" href="assets/fonts/InstrumentSans-Medium.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="assets/css/experience.css"><script src="assets/js/experience.js" defer></script></head><body>{header(current)}<main id="main">{body}</main>{footer()}</body></html>'''
 (OUT/file).write_text(text,encoding='utf-8')

def product_card(p):
 return f'<a class="product-card" href="{p["slug"]}.html" style="--product:#{p["accent"]}"><div class="product-top"><img src="assets/products/{p["icon"]}" alt="" width="56" height="56" loading="lazy"><span class="card-arrow" aria-hidden="true">↗</span></div><p class="product-name">{e(p["name"])}</p><h3>{e(p["promise"])}</h3><span class="product-category">{e(p["index"])}</span></a>'

def proofwall():
 return '<div class="proof-wall">'+''.join(f'<a href="{p["slug"]}.html"><img src="assets/products/{p["icon"]}" alt="" width="42" height="42" loading="lazy"><span>{e(p["name"])}</span></a>' for p in products[:-1])+'</div>'

def steps():
 return '<div class="delivery-steps">'+''.join(f'<article><span class="step-number">0{i}</span><h3>{t}</h3><p>{d}</p></article>' for i,t,d in [(1,'Understand the work.','Follow the real service, decision or handoff. Find what is missing and agree what improvement will look like.'),(2,'Choose the right route.','Deploy a ready system, connect existing tools, or engineer the part that does not yet exist.'),(3,'Put it to work.','Confirm the scope, responsibilities and acceptance checks. Test with the people who will use it.'),(4,'See what changed.','Track the agreed measures. Give your team a clear way to operate, support and improve the system.')])+'</div>'

hero='''<section class="hero" data-hero><picture><source media="(max-width:700px)" srcset="assets/brand/hero-mobile.webp"><img class="hero-image" src="assets/brand/hero.webp" alt="" fetchpriority="high" width="1672" height="941"></picture><div class="hero-wash"></div><div class="hero-copy"><p class="eyebrow">Product Engineering. Without Limits.</p><h1>Software that<br>improves operations<br>and launches<br><em>new services.</em></h1><p class="lede">Bring us the service, decision or handoff that needs to work better. We deploy a ready system where it fits, connect what is fragmented, or engineer what is missing.</p><div class="actions">'''+action('Show us the work','contact.html')+'''<a class="text-link" href="#systems">Explore the systems <span aria-hidden="true">↓</span></a></div></div><div class="hero-bottom"><span>For businesses, institutions<br>and governments.</span><span class="hero-note">Find what is missing.<br>Make more possible.</span></div></section>'''

outcomes='''<section class="section outcomes"><div class="section-head"><div><p class="eyebrow">What AlphaIT improves</p><h2>Better work.<br>More possibility.</h2></div><p>Not every opportunity starts with a broken system. Sometimes it is a service you could launch, a cost you could avoid, or work you cannot yet see.</p></div><div class="outcome-grid">'''+''.join(f'<article><span class="small-number">0{i}</span><h3>{t}</h3><p>{d}</p><span class="outcome-tag">{tag}</span></article>' for i,t,d,tag in [(1,'Recover the work you are losing.','Find missed enquiries, abandoned journeys and handoffs that stop work from reaching completion.','Revenue & service recovery'),(2,'Remove avoidable cost and delay.','Connect information and tasks so teams spend less time repeating, chasing and correcting work.','Cost & efficiency'),(3,'See what needs attention.','Bring evidence, feedback and responsibility together so people can make better decisions.','Visibility & control'),(4,'Launch a new service.','Use a built system or a focused new build to turn an opportunity into something customers can use.','New offerings & growth')])+'</div></section>'

mapsection='''<section class="section route-section" id="in-action"><div class="section-head"><div><p class="eyebrow">From a need to a working system</p><h2>See the route<br>to better work.</h2></div><p>Choose an example. See what is missing, what we put in place and what your team can measure.</p></div><div class="route-tabs" role="tablist" aria-label="Operation examples"><button role="tab" aria-selected="true" aria-controls="route-panel" id="route-tab-0" data-route="0">Improve a service</button><button role="tab" aria-selected="false" aria-controls="route-panel" id="route-tab-1" tabindex="-1" data-route="1">Connect a decision</button><button role="tab" aria-selected="false" aria-controls="route-panel" id="route-tab-2" tabindex="-1" data-route="2">Launch an offering</button></div><div class="route-stage" role="tabpanel" id="route-panel" aria-labelledby="route-tab-0" tabindex="0"><div class="route-track" aria-hidden="true"><span></span></div><div class="route-node"><span class="route-label">01 / The need</span><h3 data-route-title="0">People report an issue.</h3><p data-route-body="0">Feedback arrives, but the right team does not see it.</p></div><div class="route-node route-core"><span class="route-label">02 / Put the system to work</span><img data-route-icon src="assets/products/verdika-mark.png" width="56" height="56" alt=""><h3 data-route-title="1">Verdika connects the feedback.</h3><p data-route-body="1">Capture the experience, see the pattern and route it to the responsible stakeholder.</p><a data-route-link class="text-link" href="verdika.html">Explore Verdika ↗</a></div><div class="route-node"><span class="route-label">03 / See the change</span><h3 data-route-title="2">The right people can act.</h3><p data-route-body="2">Measure response time, recurring issues and whether feedback reaches the right team.</p></div></div><div class="route-caption"><span>Illustrative workflows. Each deployment is scoped to your organisation.</span><span>Explore all three ↑</span></div></section>'''

home=hero+outcomes+mapsection+'''<section class="section systems" id="systems"><div class="section-head"><div><p class="eyebrow">Built by AlphaIT Engineering</p><h2>Not just ideas.<br>Systems we have built.</h2></div><div><p>From customer experience to credit decisions, transport and skills. Explore the system that fits your next step.</p><a class="text-link" href="platforms.html">Meet every system ↗</a></div></div>'''+proofwall()+'''<div class="featured-system"><div><p class="eyebrow">Built systems. Focused engineering.</p><h3>You may not need<br>to start from scratch.</h3></div><p>We can deploy a ready system, configure it for your organisation and connect it to the way you work. Where something is missing, we architect and build it.</p><a class="circle-link" aria-label="Explore all AlphaIT systems" href="platforms.html">↗</a></div></section><section class="section approach" id="approach"><div class="section-head"><div><p class="eyebrow">How we work</p><h2>Start with the work.<br>Build around the outcome.</h2></div><p>First, agree what needs to improve and how you will know it worked. That could mean faster service, fewer errors, lower cost or more completed sales.</p></div>'''+steps()+'</section>'+close()

catalog='''<section class="page-intro"><p class="eyebrow">Our systems</p><h1>Built by us.<br>Put to work <em>by you.</em></h1><p class="lede">Each system solves a different need. Explore what it does, who it is for and what changes when you put it to work.</p></section><section class="section catalog-section"><div class="catalog-label"><span>AlphaIT product portfolio</span><span>Ready systems + focused engineering</span></div><div class="product-grid">'''+''.join(product_card(p) for p in products)+'''</div><p class="portfolio-note">These are AlphaIT-built products, not customer logos. Deployment scope, integrations, data permissions, timing and commercial terms are agreed for each organisation.</p></section>'''+close('Find the system<br>that fits your work.','Tell us what you need to improve or launch. We will help you assess the fit before you commit to a deployment.')
page('index.html','Software that improves operations and launches new services','AlphaIT Engineering deploys, connects and builds software for businesses, institutions and governments.',home)
page('platforms.html','Our systems','Explore the products built by AlphaIT Engineering and what they can do for your organisation.',catalog,'Our systems')

for p in products:
 body=f'''<section class="product-hero" style="--product:#{p['accent']}"><a class="back-link" href="platforms.html">← All systems</a><div class="product-identity"><img src="assets/products/{p['icon']}" width="78" height="78" alt=""><p>{e(p['name'])}</p></div><div class="product-hero-grid"><div><h1>{e(p['promise'])}</h1><div class="actions">{action('Discuss '+('your build' if p['icon_key']=='alphait' else 'a deployment'),'contact.html?product='+p['slug'])}<a class="text-link" href="#system-in-action">See how it works ↓</a></div></div><div class="product-summary"><p>{e(p['description'])}</p><div class="for-label">Who it is for</div><p>{e(p['buyer'])}</p></div></div></section><section class="section product-workflow" id="system-in-action"><p class="eyebrow">The system in action</p><h2>What changes<br>in the real work.</h2><div class="workflow-columns">'''+''.join(f'<article><span class="step-number">0{i}</span><h3>{title}</h3><p>{e(p[key])}</p></article>' for i,title,key in [(1,'The situation','situation'),(2,'What the system does','system'),(3,'What becomes visible','visible')])+f'''</div><div class="measure-panel"><p class="eyebrow">Agree what success looks like</p><h3>Make the improvement visible.</h3><p>{e(p['measure'])}</p><span>Measures are agreed for your deployment. They are not guaranteed results.</span></div></section><section class="section product-next"><div><p class="eyebrow">From fit to deployment</p><h2>Your work.<br>Your requirements.</h2></div><div><p>We confirm the people, data, connections and permissions needed. Then we agree the scope, delivery plan, acceptance checks and support.</p><p>Where the ready system does not fully fit, AlphaIT can engineer the missing connection or capability.</p>'''+('<p>Credit providers retain their lending decisions and risk. Deployment is subject to applicable requirements and agreed policies.</p>' if p['icon_key'] in ['lsi','lisbon','liscredit'] else '')+f'''</div></section>'''+close('Put '+('your idea' if p['icon_key']=='alphait' else e(p['name']))+'<br>to work.','Bring us your use case. We will show you the relevant workflow and agree the right next step.')
 page(p['slug']+'.html',p['name'],p['promise'],body,'Our systems')

company='''<section class="page-intro"><p class="eyebrow">AlphaIT Engineering</p><h1>Find what is missing.<br><em>Build what is next.</em></h1><p class="lede">We help businesses, institutions and governments improve how they work and bring new services into the world.</p></section><section class="company-image"><img src="assets/brand/hero.webp" alt="AlphaIT architectural brand artwork: a clear route through connected structures" width="1672" height="941"><span>Product Engineering. Without Limits.</span></section><section class="section company-story"><div><p class="eyebrow">What we do</p><h2>Understand the need.<br>Engineer the answer.</h2></div><div><p>Sometimes the problem is obvious. Sometimes the missing connection, repeated task or untapped opportunity is harder to see.</p><p>AlphaIT studies the real operation, architects the solution and puts the technology to work. We can start with a system we have already built, connect the tools you already use, or build what does not yet exist.</p><p>The aim is practical: improve service, reduce avoidable cost, make work visible and enable new sources of value.</p></div></section><section class="section company-proof"><p class="eyebrow">Our work is already taking shape</p><h2>A portfolio of built systems.<br>A foundation for what comes next.</h2>'''+proofwall()+'''<a class="text-link" href="platforms.html">Explore what we have built ↗</a></section>'''+close()
page('company.html','Company','AlphaIT Engineering identifies what is missing, architects the solution and builds technology around the real operation.',company,'Company')

approach='''<section class="page-intro"><p class="eyebrow">How we work</p><h1>The right system.<br>For the <em>real work.</em></h1><p class="lede">A ready product where it fits. A connected solution where work is fragmented. A focused build where something is missing.</p></section><section class="section">'''+steps()+'''</section><section class="section engagement-routes"><p class="eyebrow">Three ways to begin</p><h2>Choose the starting point.<br>Not the technology first.</h2><div class="workflow-columns"><article><span class="step-number">01</span><h3>Deploy a ready system.</h3><p>Start from an AlphaIT-built product. Configure the roles, policies and connections around your organisation.</p><a class="text-link" href="platforms.html">Explore the systems ↗</a></article><article><span class="step-number">02</span><h3>Connect what exists.</h3><p>Bring the right people, data and tools together. Close the handoff that is creating delays, repeat work or blind spots.</p><a class="text-link" href="contact.html?product=connect">Discuss your operation ↗</a></article><article><span class="step-number">03</span><h3>Engineer what is missing.</h3><p>Define and build a new capability or service when an existing system does not fully fit.</p><a class="text-link" href="business-systems-engineering.html">Explore a focused build ↗</a></article></div></section><section class="section company-story"><div><p class="eyebrow">Before work begins</p><h2>Clarity on the work.<br>Clarity on the commitment.</h2></div><div><p>We agree the scope, responsibilities, delivery stages and acceptance checks. We confirm required integrations, access, data permissions and operating requirements.</p><p>Pricing follows the agreed scope. Licensing, configuration, custom engineering and ongoing support are set out clearly in the proposal.</p><p>We also agree what to measure, so your team can see whether the intended change is happening.</p></div></section>'''+close()
page('engagements.html','How we work','Deploy a ready AlphaIT system, connect existing tools or engineer the missing capability.',approach,'How we work')

contact_source=SOURCE/'AlphaIT Engineering Website - Aether Mineral 2026/contact.html'
old_contact=(contact_source if contact_source.exists() else OUT/'contact.html').read_text(encoding='utf-8')
key=re.search(r'name="access_key"\s+value="([^"]+)"',old_contact)
assert key, 'Existing contact-form key missing; do not replace with fake service'
contact='''<section class="page-intro contact-intro"><p class="eyebrow">Start a conversation</p><h1>Show us<br><em>the work.</em></h1><p class="lede">A process to improve. A system to deploy. A new service to launch. Tell us where you want to go.</p></section><section class="section contact-layout"><div class="contact-details"><p class="eyebrow">Speak with AlphaIT</p><h2>Start with what<br>needs to change.</h2><p>You do not need a technical brief. A clear description of the work, the people involved and the result you want is enough to begin.</p><a class="contact-line" href="mailto:projects@alphaitengineering.com"><span aria-hidden="true">✉</span><span>projects@alphaitengineering.com</span></a><a class="contact-line" href="https://wa.me/254792989676" target="_blank" rel="noopener"><span aria-hidden="true">↗</span><span>Message us on WhatsApp</span></a><a class="text-link" href="AlphaIT-Company-and-Product-Profile.pdf" target="_blank" rel="noopener">Download the company profile ↗</a></div><form id="projectForm" action="https://api.web3forms.com/submit" method="POST"><input type="hidden" name="access_key" value="'''+e(key.group(1))+'''"><input type="hidden" name="subject" value="AlphaIT website project enquiry"><input type="checkbox" name="botcheck" class="botcheck" tabindex="-1" aria-hidden="true"><div class="form-pair"><label>Your name<input name="name" autocomplete="name" required maxlength="150"></label><label>Organisation<input name="company" autocomplete="organization" required maxlength="200"></label></div><label>Work email<input type="email" name="email" autocomplete="email" required maxlength="254"></label><label>Phone / WhatsApp <span>(optional)</span><input type="tel" name="phone" autocomplete="tel" maxlength="60"></label><label>What would you like to explore?<select name="interest" id="interest"><option value="">Help me find the right starting point</option value="connect">Connect an existing operation</option>'''+''.join(f'<option value="{p["slug"]}">{e(p["name"])}</option>' for p in products)+'''</select></label><label>What would you like to improve or launch?<textarea name="message" rows="5" required maxlength="5000" placeholder="Tell us about the work and what you want to change."></textarea></label><p class="form-note">Your details and message are sent to AlphaIT through Web3Forms so we can respond to your enquiry. Please do not include passwords, financial records or other sensitive information.</p><button type="submit" class="button primary">Send your enquiry <span aria-hidden="true">↗</span></button><p id="formStatus" role="status" aria-live="polite"></p></form></section>'''
contact=contact.replace('</option value="connect">','</option><option value="connect">')
page('contact.html','Contact','Tell AlphaIT Engineering what you want to improve or launch.',contact)
page('404.html','Page not found','Find the right AlphaIT page.','<section class="page-intro"><p class="eyebrow">404 / Page not found</p><h1>Let’s get you<br>back on track.</h1><div class="actions">'+action('Back to AlphaIT','index.html')+'<a class="text-link" href="platforms.html">Explore our systems ↗</a></div></section>')
# Preserve the old proof route as the product proof catalogue; the site's real work is its portfolio.
page('proof.html','Built by AlphaIT','Explore the systems built by AlphaIT Engineering.',catalog,'Our systems')

Image.open(OUT/'assets/brand/hero.png').convert('RGB').save(OUT/'assets/brand/hero.webp',quality=86,method=6)
im=Image.open(OUT/'assets/brand/hero.png').convert('RGB'); im.thumbnail((1000,1000)); im.save(OUT/'assets/brand/hero-mobile.webp',quality=83,method=6)
(ROOT/'products.json').write_text(json.dumps(products,ensure_ascii=False,indent=2),encoding='utf-8')
print(f'Generated {len(list(OUT.glob("*.html")))} pages from the approved customer profile.')
